### PR TITLE
Drop things from the queue when completed

### PR DESCRIPTION
**Pull request by dramich**
Issue: https://github.com/rancher/rancher/issues/26633
https://github.com/rancher/rancher/issues/26577

### CODE REVIEW

**Comment by dramich** [comment]
@ibuildthecloud Can you take a look at this? I can't request reviewers in this repo.

**Comment by ibuildthecloud** [comment]
Do you have more context on why the enqueueAfter change?

**Comment by dramich** [comment]
To try again, if you want to just mark the object as done regardless I can do that.

**Comment by ibuildthecloud** [comment]
Ah, so the memory leak is that we don't ever call done? I don't think we want to reenque. I'd just always call done.

**Pull request merged**
